# Generated by Django 4.2 on 2023-06-10 19:04

from django.db import migrations, models

# not necessary
class Migration(migrations.Migration):

    dependencies = [
        ('smart_images', '0002_alter_photo_description_alter_photo_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('vector', models.BinaryField()),
            ],
        ),
    ]
